### ISSUE TITLE
1.17 Please?

### ISSUE THREAD

**Issue by Monster-Zer0** [P03W/altlore#1]
Im working on a 1.17 modpack right now that involves lore and this would be perfect.

just creating an issue to let you know there is interest in this mod and it is worth updating.

thanks.

**Comment by SilverAndro** [comment]
Hi thanks for taking interest!

Does the mod crash on 1.17 currently or does it simply need to be tagged in curseforge?

**Comment by SilverAndro** [comment]
Seems to work fine on 1.17 from a quick test, so ill mark as supported

If something goes wrong just say so
